project:
  type: manuscript
  render:
    - "!notebooks_private/"

execute:
  enabled: true

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default
