project:
  type: manuscript
  render:
    - "*.ipynb" 
    - "!./internal/"

execute:
  enabled: false

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  arxiv-pdf: 
    linenumbers: true # Add (continuous) line numbers?
    doublespacing: false # Double space the PDF output?
    runninghead: "Task-structure preferences" # The text on the top of each page of the output
    authorcols: false # Should authors be listed in a single column (default) or in multiple columns (`authorcols: true`)


